# aws-cli - CI Build
# https://github.com/ArtiomL/aws-cli
# Artiom Lichtenstein
# v1.0.1, 09/10/2019

sudo: required

env:
  global:
  - REPO="artioml/aws-cli"
  - secure: "ZIAT3naTMjGu7LLYzXhzQlSX6/mGNZX91lV3IoQL6cW+HPgzGVFwfF8BaP5onuNkw2PAMcEztuqVYpifdH64Opj8fP4VZIDy7VAuoe06AmCfxLF7mrdf/NOzh3EuaSgPZlJYOIWe9gxt2PI/4MFjHCGi6aPIJWwAgmSc2+KpYB4QehZLGWHXl9nqSwBSZ6ZUcJbQZzPXSdSDeEDPwXCNXGjPu5fGiJbW19dOsjQVmZQwuqFtfmG+3qbNJHCeSI0VWAaMtaMv7eryPJA9X5yL+MogT9dUNGRUbSv4eJ9g1/QwndUNXgkd5kON3q57hvl4KWTNskogLjscfPF2sOzYkIw8/llb0PC5X4QXHuV3fpznHQs2IH6szxhfMp7AnC1VhtoU4LyvALW/xk5uhmo0zHsxIf8rTlQKz4V8wTOpaPhWr5I/hGWLRAHsmEj6jQTvThLUbMZ64RPtPVNJrQDMALdhLzOTRwnU5USUqTiOpi6cVk0GJ/VyL2809XMrEBpXt7I3EsJx/TS9NFkCJA+H/orpxY9KwzIZKj9LZvpl1g8/DfgVf7VezXlQ+MGPI7Z+/PnPODZJgQ2VwhtXtmL2b7qyfXcwlSSrmM41MZOALMSG02bWYQyjg3mqmkJjN8Xm59Rdr3BsLK35WoPJI0ht01OZZvZIMXqIA+PK8ivElVk="
  - secure: "LZAty+iFeJ9aZ1FeL2qmxdUZ/hiRy9rJXXoSxLvMhxSxQh76vtj++tn7QdApQOxDMBB0x2NptOOgtDRBvopsQIb5t5E/IuLhHHC8rPC+38IpWdUSQ19NhRYWkdec92EpjPprV9UrOUqySZklDwMM3IvOUaQa9fWpVGHLRW6nlklH4zJlgKkkIdYrn1T41BSxrc8QnOSmAclS8kRebT3HbYs23nXSCxGwgxcOKseTUl5+G92lATP+1P585JUWFOmLib21NDQXlz0MBffXYq/pAsWJ2p7KxQOFJitU14S46vXauEZmDwPkY67VOXXtKZzz8xoytw512Oi0myzasboXOr8VDoZ4dW6opUu6U0tjlYdCic8Am3SDW8FJEO7qakmrWkLqZhNvRc7FnF64HZPVDfQuCDHpSLnU5FqfyzdWxS/SWlfr0g2d/hRvaQMwz+vltZ/yyMFhpXhZtUdvd3o9Epzsrdpvls1YZWULcSSSIfi/fZ4SUl0fFaS5QMuZkhmJT1oGkFG5IMHsYS3y0ineTX4PLvfjnpcNo3If3kU0qmVduqNjcLSIxHDGc+ZKA4P2j6oH5CH6QLcc90/ewlwlBdskZ6KNLKIQ1p0Qf/2JZu6KTceNcXPQt03CI+pcoq48u5f0zdm7gavUwUO1XrC/NpZYmWbul2RyVB8FxFAq+9M="

services:
  - docker

before_script:
  - chmod +x test/run.sh

script:
  - docker build -t $REPO .
  - test/run.sh

after_success:
  - docker images
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASS;
    docker push $REPO;
    fi

notifications:
  slack:
    secure: "dJ6GNpuA+GhkuAWdKjbADFmBeCpOjmhyIKkoq5t2nHflR71ovuTt6GPY0DyJ7p1JYqfiVNnyq6335rblijc8phphNEyoAVGQKleif0NMjyx22fPfvUq5GdSMZdnczSdeQERXUeHZfUuGAI/IpJU6ko8/UFaMZfwFyg8cbJEgX64B6ULRTSySmOeRIWroSHDfvqjPa2/u1i7xBWhcdbMrVa0GaIuq/iV3v7RjWifFFjSFEr/lgO/M82Ko+URaOIkr3H4Do5CeLMxhQIBrcS+iRTwOYG4+Vkh8ldAeXdrH5fVbnssKv+WaZIQxbfgILPT3qIRcrD8Az7oiEmRs6xvb6nLmKlMsgBPO3stkx3zLn/WqNh5izQVvs59GHk+ssYe/kxFnX9kY8rFDdQP8oMgFKoFr58G0ur0FJAQN2RUw5vO1SwfR8HgyK+V0ld7KRlaYGyKM274k2PNuBV4Rl5vv9JwZTXnXNMO1vA393oQD/git941a37LyG3UDcdKKHT9F3FFu/aqf9XmlMDGzmoqtajt67fpU94TbEa/USDcYXV7hI8yS0AZJVI12sLgdTgflI9K67RmmVsVys9YTIXey4ANTwpuQdh7Y7SW6IfMpoIEr4dp+7YUMPzVPup3pbzFCmHJoOHGdMaAcx/IjHrnaPkYwR1MVtgAOAr9Xt1aVKXU="
